### ISSUE TITLE
Foundations not updated on move

### ISSUE THREAD

**Issue by mcdemarco** [fimion/vue-solitaire#48]
The foundation ("final") stacks aren't updated when a card is moved to the foundation unless it's the initial ace.  However the correct top card is shown after a reload of the page.  This seems to be a recent regression; it was working in https://github.com/fimion/vue-solitaire/commit/80e671dec520f974f7c8f8376134454bd19fcf05

**Comment by fimion** [comment]
goodness! Likely a side effect of migrating to vue 3. Let me dig into this. thanks!

**Comment by fimion** [comment]
I believe I found the issue and it should all be working again!
